#!/bin/bash
echo "Creating properties file..."
echo
if [ "$GITHUB_TOKEN" = "" ]; then
  echo "You must specify a Github token using the env variable \$GITHUB_TOKEN.
If you don't have a token, generate one at https://github.com/settings/tokens"
  exit -1
fi
if [ "$SLACK_WEBHOOK_URL" = "" ]; then
  echo "You must specify a Slack webhook URL using the env variable \$SLACK_WEBHOOK_URL.
If you don't have one yet, generate it at https://slack.com/apps/new/A0F7XDUAZ-incoming-webhooks"
  exit -1
fi

# create a config file with the token and url
echo "github.token=$GITHUB_TOKEN" > resources/config.properties
echo "slack.webhook.url=$SLACK_WEBHOOK_URL" >> resources/config.properties

echo "Creating uberjar:"
echo

lein uberjar
cp $PWD/target/uberjar/tako-*-standalone.jar $PWD/target/tako.jar

echo
echo "Uploading as AWS lambda"

# config variables
: ${AWS_REGION:=us-east-1}
: ${TAKO_FN_NAME:=tako}

aws lambda update-function-code \
  --region $AWS_REGION \
  --function-name $TAKO_FN_NAME \
  --publish \
  --zip-file fileb://$PWD/target/tako.jar

echo
echo "Updating AWS lambda configuration"

aws lambda update-function-configuration \
  --region $AWS_REGION \
  --function-name $TAKO_FN_NAME \
  --memory-size 256 \
  --timeout 60
